import { RemoteServer, NginxNewSiteConfig, NginxSiteTestResult, NginxSiteDeployResult } from '../src/types';
import { runAdaptiveSshCommand } from './linuxServerMonitor';
import { discoverNginxInstallation } from './nginxDiscovery';

/**
 * Sanitize domain name or filename to strictly prevent shell or path injection
 */
export function sanitizeDomainName(domain: string): string {
  const cleaned = domain.trim().toLowerCase().replace(/[^a-z0-9_\-\.]/g, '');
  if (!cleaned) {
    throw new Error('Invalid domain name provided.');
  }
  return cleaned;
}

/**
 * Formats a clean, robust, and idiomatic Nginx configuration block
 */
export function generateNginxSiteConfig(config: NginxNewSiteConfig): string {
  const primaryDomain = sanitizeDomainName(config.domain);
  const rawAliases = config.serverNames || [];
  const validAliases = rawAliases
    .map((a) => a.trim().toLowerCase().replace(/[^a-z0-9_\-\.]/g, ''))
    .filter((a) => a && a !== primaryDomain);

  const allDomains = [primaryDomain, ...validAliases].join(' ');
  const port = Math.min(Math.max(config.port || (config.enableSsl ? 443 : 80), 1), 65535);
  const isSsl = Boolean(config.enableSsl);
  const clientMaxBody = config.clientMaxBodySize ? config.clientMaxBodySize.trim() : '64M';

  const lines: string[] = [];

  lines.push('# ==============================================================================');
  lines.push(`# Nginx Virtual Host Configuration`);
  lines.push(`# Domain: ${primaryDomain}`);
  lines.push(`# Type: ${config.siteType.toUpperCase()}`);
  lines.push(`# Generated by NetTopology Nginx Site Wizard on ${new Date().toISOString()}`);
  lines.push('# ==============================================================================');
  lines.push('');

  // 1. Force HTTPS Redirect block if SSL enabled and redirect requested
  if (isSsl && config.forceHttpsRedirect) {
    lines.push('server {');
    lines.push('    listen 80;');
    lines.push(`    server_name ${allDomains};`);
    lines.push('    return 301 https://$host$request_uri;');
    lines.push('}');
    lines.push('');
  }

  // 2. Main Server Block
  lines.push('server {');
  
  // Listen directive
  let listenDirective = `    listen ${port}`;
  if (isSsl) {
    listenDirective += ' ssl';
  }
  if (config.isDefaultServer) {
    listenDirective += ' default_server';
  }
  listenDirective += ';';
  lines.push(listenDirective);

  // IPv6 listen
  let listenIpv6 = `    listen [::]:${port}`;
  if (isSsl) {
    listenIpv6 += ' ssl';
  }
  if (config.isDefaultServer) {
    listenIpv6 += ' default_server';
  }
  listenIpv6 += ';';
  lines.push(listenIpv6);

  lines.push(`    server_name ${allDomains};`);
  lines.push('');

  // SSL Certificate directives
  if (isSsl) {
    const certPath = config.sslCertPath?.trim() || `/etc/letsencrypt/live/${primaryDomain}/fullchain.pem`;
    const keyPath = config.sslKeyPath?.trim() || `/etc/letsencrypt/live/${primaryDomain}/privkey.pem`;
    lines.push('    # SSL / TLS Security Configuration');
    lines.push(`    ssl_certificate ${certPath};`);
    lines.push(`    ssl_certificate_key ${keyPath};`);
    lines.push('    ssl_protocols TLSv1.2 TLSv1.3;');
    lines.push('    ssl_ciphers HIGH:!aNULL:!MD5;');
    lines.push('    ssl_prefer_server_ciphers on;');
    lines.push('    ssl_session_cache shared:SSL:10m;');
    lines.push('    ssl_session_timeout 1d;');
    lines.push('');
  }

  // Security Headers
  if (config.enableSecurityHeaders !== false) {
    lines.push('    # Hardened Security Headers');
    lines.push('    add_header X-Frame-Options "SAMEORIGIN" always;');
    lines.push('    add_header X-Content-Type-Options "nosniff" always;');
    lines.push('    add_header X-XSS-Protection "1; mode=block" always;');
    lines.push('    add_header Referrer-Policy "strict-origin-when-cross-origin" always;');
    lines.push('');
  }

  // Performance & Upload Limits
  lines.push(`    # Limits & Buffering`);
  lines.push(`    client_max_body_size ${clientMaxBody};`);
  if (config.enableGzip !== false) {
    lines.push('    gzip on;');
    lines.push('    gzip_vary on;');
    lines.push('    gzip_proxied any;');
    lines.push('    gzip_comp_level 6;');
    lines.push('    gzip_types text/plain text/css application/json application/javascript text/xml application/xml+rss text/javascript image/svg+xml;');
  }
  lines.push('');

  // Diagnostic Logs
  lines.push('    # Logging');
  lines.push(`    access_log /var/log/nginx/${primaryDomain}.access.log;`);
  lines.push(`    error_log /var/log/nginx/${primaryDomain}.error.log warn;`);
  lines.push('');

  // Site Payload: Proxy or Static
  if (config.siteType === 'proxy') {
    const rawTarget = config.proxyPassUrl?.trim() || 'http://127.0.0.1:3000';
    const proxyTimeout = config.proxyTimeoutSec || 60;

    lines.push('    # Reverse Proxy Gateway');
    lines.push('    location / {');
    lines.push(`        proxy_pass ${rawTarget};`);
    
    if (config.standardHeaders !== false) {
      lines.push('        proxy_set_header Host $host;');
      lines.push('        proxy_set_header X-Real-IP $remote_addr;');
      lines.push('        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;');
      lines.push('        proxy_set_header X-Forwarded-Proto $scheme;');
      lines.push('        proxy_set_header X-Forwarded-Host $host;');
      lines.push('        proxy_set_header X-Forwarded-Port $server_port;');
    }

    if (config.enableWebSocket !== false) {
      lines.push('        # WebSocket Upgrades Support');
      lines.push('        proxy_http_version 1.1;');
      lines.push('        proxy_set_header Upgrade $http_upgrade;');
      lines.push('        proxy_set_header Connection "upgrade";');
    }

    lines.push(`        proxy_connect_timeout ${proxyTimeout}s;`);
    lines.push(`        proxy_send_timeout ${proxyTimeout}s;`);
    lines.push(`        proxy_read_timeout ${proxyTimeout}s;`);

    if (config.proxyBuffering === false) {
      lines.push('        proxy_buffering off;');
    }

    lines.push('    }');
  } else if (config.siteType === 'static') {
    const docRoot = config.documentRoot?.trim() || `/var/www/${primaryDomain}`;
    const indexes = config.indexFiles?.trim() || 'index.html index.htm';

    lines.push('    # Static Files Hosting');
    lines.push(`    root ${docRoot};`);
    lines.push(`    index ${indexes};`);
    lines.push('');
    lines.push('    location / {');
    if (config.enableSpaFallback) {
      lines.push('        # SPA Fallback Routing');
      lines.push('        try_files $uri $uri/ /index.html;');
    } else {
      lines.push('        try_files $uri $uri/ =404;');
    }
    if (config.enableAutoindex) {
      lines.push('        autoindex on;');
    }
    lines.push('    }');
    lines.push('');
    lines.push('    # Cache static assets');
    lines.push('    location ~* \\.(?:css|js|jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc|woff|woff2|ttf)$ {');
    lines.push('        expires 1M;');
    lines.push('        access_log off;');
    lines.push('        add_header Cache-Control "public";');
    lines.push('    }');
  }

  // Custom Directives if provided
  if (config.customDirectives?.trim()) {
    lines.push('');
    lines.push('    # Custom Directives');
    const customLines = config.customDirectives.trim().split('\n');
    for (const cLine of customLines) {
      lines.push(`    ${cLine}`);
    }
  }

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Tests candidate Nginx configuration on the remote host in a standalone test context
 */
export async function testNginxSiteConfig(
  server: RemoteServer,
  config: NginxNewSiteConfig,
  ephemeralPassword?: string
): Promise<NginxSiteTestResult> {
  const domain = sanitizeDomainName(config.domain);
  const discovery = await discoverNginxInstallation(server, ephemeralPassword);
  const nginxBinary = discovery.binaryPath || '/usr/sbin/nginx';

  const configContent = config.customConfigSnippet?.trim() || generateNginxSiteConfig(config);
  const base64Content = Buffer.from(configContent, 'utf-8').toString('base64');

  const timestamp = Date.now();
  const candidatePath = `/tmp/test_site_${timestamp}.conf`;
  const wrapperPath = `/tmp/test_wrapper_${timestamp}.conf`;

  // Python test script that writes wrapper, tests, and captures full diagnostic output
  const testScript = `python3 - << 'PYEOF'
import os, sys, subprocess, base64, json

binary = "${nginxBinary}"
candidate_path = "${candidatePath}"
wrapper_path = "${wrapperPath}"
b64_data = """${base64Content}"""

try:
    content = base64.b64decode(b64_data.encode('ascii')).decode('utf-8')
    with open(candidate_path, 'w', encoding='utf-8') as f:
        f.write(content)
        
    wrapper_content = f"""
events {{
    worker_connections 1024;
}}
http {{
    include {candidate_path};
}}
"""
    with open(wrapper_path, 'w', encoding='utf-8') as f:
        f.write(wrapper_content)
        
    # Execute syntax test
    cmd = [binary, "-t", "-c", wrapper_path]
    res = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, timeout=10)
    
    out = (res.stdout or '') + "\\n" + (res.stderr or '')
    is_valid = (res.returncode == 0) and ("syntax is ok" in out.lower())
    
    result = {
        "isValid": is_valid,
        "output": out.strip(),
        "exitCode": res.returncode
    }
except Exception as e:
    result = {
        "isValid": False,
        "output": f"Execution error: {str(e)}",
        "exitCode": -1
    }
finally:
    for p in [candidate_path, wrapper_path]:
        if os.path.exists(p):
            try:
                os.remove(p)
            except:
                pass

print("===TEST_JSON_START===")
print(json.dumps(result))
print("===TEST_JSON_END===")
PYEOF
`;

  try {
    const rawOut = await runAdaptiveSshCommand(server, testScript, ephemeralPassword, 15000);
    if (rawOut.includes('===TEST_JSON_START===') && rawOut.includes('===TEST_JSON_END===')) {
      const jsonStr = rawOut.split('===TEST_JSON_START===')[1].split('===TEST_JSON_END===')[0].trim();
      const parsed = JSON.parse(jsonStr);

      return {
        success: true,
        isValid: parsed.isValid,
        testOutput: parsed.output,
        generatedConfig: configContent,
        targetFilePath: `/etc/nginx/sites-available/${domain}.conf`,
      };
    }
  } catch (err: any) {
    console.warn(`[NginxSiteWriter] Remote syntax test failed on ${server.id}:`, err?.message || err);
    return {
      success: false,
      isValid: false,
      testOutput: err?.message || 'Failed to execute remote test',
      generatedConfig: configContent,
      targetFilePath: `/etc/nginx/sites-available/${domain}.conf`,
      error: err?.message || 'Remote syntax test failed',
    };
  }

  return {
    success: false,
    isValid: false,
    testOutput: 'No valid output returned from remote syntax checker',
    generatedConfig: configContent,
    targetFilePath: `/etc/nginx/sites-available/${domain}.conf`,
    error: 'Failed to verify syntax',
  };
}

/**
 * Safely deploys an Nginx virtual host with atomic rollback in case of syntax rejection
 */
export async function deployNginxSite(
  server: RemoteServer,
  config: NginxNewSiteConfig,
  ephemeralPassword?: string
): Promise<NginxSiteDeployResult> {
  const domain = sanitizeDomainName(config.domain);
  const discovery = await discoverNginxInstallation(server, ephemeralPassword);
  const nginxBinary = discovery.binaryPath || '/usr/sbin/nginx';

  const configContent = config.customConfigSnippet?.trim() || generateNginxSiteConfig(config);
  const base64Content = Buffer.from(configContent, 'utf-8').toString('base64');
  const autoReload = config.autoReloadService !== false;

  const deployScript = `python3 - << 'PYEOF'
import os, sys, subprocess, base64, json, shutil

binary = "${nginxBinary}"
domain = "${domain}"
b64_data = """${base64Content}"""
auto_reload = ${autoReload ? 'True' : 'False'}

result = {
    "success": False,
    "deployedFilePath": "",
    "symlinkPath": None,
    "syntaxTestPassed": False,
    "syntaxOutput": "",
    "serviceReloaded": False,
    "reloadOutput": "",
    "error": None
}

try:
    content = base64.b64decode(b64_data.encode('ascii')).decode('utf-8')
    
    # 1. Determine site directory convention
    sites_avail = "/etc/nginx/sites-available"
    sites_enabled = "/etc/nginx/sites-enabled"
    conf_d = "/etc/nginx/conf.d"
    
    has_debian_style = os.path.isdir(sites_avail) and os.path.isdir(sites_enabled)
    
    target_file = ""
    symlink_file = None
    backup_file = None
    
    if has_debian_style:
        target_file = os.path.join(sites_avail, f"{domain}.conf")
        symlink_file = os.path.join(sites_enabled, f"{domain}.conf")
    else:
        if not os.path.isdir(conf_d):
            os.makedirs(conf_d, exist_ok=True)
        target_file = os.path.join(conf_d, f"{domain}.conf")

    result["deployedFilePath"] = target_file
    result["symlinkPath"] = symlink_file

    # Create backup if already exists
    if os.path.exists(target_file):
        backup_file = target_file + ".bak"
        shutil.copy2(target_file, backup_file)

    # Write target configuration file
    with open(target_file, 'w', encoding='utf-8') as f:
        f.write(content)
        
    # If Debian style, create symlink in sites-enabled
    if symlink_file:
        if os.path.islink(symlink_file) or os.path.exists(symlink_file):
            try:
                os.remove(symlink_file)
            except:
                pass
        os.symlink(target_file, symlink_file)
        
    # 2. Execute FULL system syntax test: nginx -t
    test_proc = subprocess.run([binary, "-t"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, timeout=12)
    test_output = (test_proc.stdout or '') + "\\n" + (test_proc.stderr or '')
    result["syntaxOutput"] = test_output.strip()
    
    is_valid = (test_proc.returncode == 0) and ("syntax is ok" in test_output.lower())
    result["syntaxTestPassed"] = is_valid
    
    if not is_valid:
        # ATOMIC ROLLBACK!
        if symlink_file and os.path.exists(symlink_file):
            try:
                os.remove(symlink_file)
            except:
                pass
                
        if backup_file and os.path.exists(backup_file):
            shutil.move(backup_file, target_file)
        else:
            if os.path.exists(target_file):
                os.remove(target_file)
                
        result["error"] = "Nginx syntax verification failed. Site changes have been automatically rolled back."
    else:
        # Success! Clean up backup
        if backup_file and os.path.exists(backup_file):
            try:
                os.remove(backup_file)
            except:
                pass
                
        result["success"] = True
        
        # 3. Reload service if requested
        if auto_reload:
            reload_cmd = ["systemctl", "reload", "nginx"]
            if not shutil.which("systemctl"):
                reload_cmd = [binary, "-s", "reload"]
            
            try:
                rel_proc = subprocess.run(reload_cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, timeout=10)
                rel_out = (rel_proc.stdout or '') + "\\n" + (rel_proc.stderr or '')
                result["serviceReloaded"] = (rel_proc.returncode == 0)
                result["reloadOutput"] = rel_out.strip()
            except Exception as re_err:
                result["serviceReloaded"] = False
                result["reloadOutput"] = str(re_err)

except Exception as ex:
    result["error"] = str(ex)

print("===DEPLOY_JSON_START===")
print(json.dumps(result))
print("===DEPLOY_JSON_END===")
PYEOF
`;

  try {
    const rawOut = await runAdaptiveSshCommand(server, deployScript, ephemeralPassword, 20000);
    if (rawOut.includes('===DEPLOY_JSON_START===') && rawOut.includes('===DEPLOY_JSON_END===')) {
      const jsonStr = rawOut.split('===DEPLOY_JSON_START===')[1].split('===DEPLOY_JSON_END===')[0].trim();
      const parsed: NginxSiteDeployResult = JSON.parse(jsonStr);
      return parsed;
    }
  } catch (err: any) {
    console.error(`[NginxSiteWriter] Site deploy error on ${server.id}:`, err?.message || err);
    return {
      success: false,
      deployedFilePath: '',
      syntaxTestPassed: false,
      syntaxOutput: err?.message || 'Deployment execution exception',
      serviceReloaded: false,
      error: err?.message || 'Site deployment failed',
    };
  }

  return {
    success: false,
    deployedFilePath: '',
    syntaxTestPassed: false,
    syntaxOutput: 'No response from deployment runner',
    serviceReloaded: false,
    error: 'Failed to deploy Nginx site',
  };
}

/**
 * Toggles a site's enabled/disabled status
 */
export async function toggleNginxSiteStatus(
  server: RemoteServer,
  siteFilePath: string,
  enable: boolean,
  ephemeralPassword?: string
): Promise<{ success: boolean; isEnabled: boolean; message: string }> {
  const discovery = await discoverNginxInstallation(server, ephemeralPassword);
  const nginxBinary = discovery.binaryPath || '/usr/sbin/nginx';

  const script = `python3 - << 'PYEOF'
import os, sys, subprocess, shutil, json

binary = "${nginxBinary}"
site_path = "${siteFilePath}"
to_enable = ${enable ? 'True' : 'False'}

res = {"success": False, "isEnabled": False, "message": ""}

try:
    filename = os.path.basename(site_path)
    sites_enabled = "/etc/nginx/sites-enabled"
    symlink_path = os.path.join(sites_enabled, filename)
    
    if os.path.isdir(sites_enabled):
        # Debian/Ubuntu style
        if to_enable:
            if not os.path.exists(symlink_path):
                os.symlink(site_path, symlink_path)
        else:
            if os.path.islink(symlink_path) or os.path.exists(symlink_path):
                os.remove(symlink_path)
    else:
        # Conf.d rename style
        if to_enable:
            if site_path.endswith('.disabled'):
                new_path = site_path[:-9]
                shutil.move(site_path, new_path)
                site_path = new_path
        else:
            if not site_path.endswith('.disabled'):
                new_path = site_path + '.disabled'
                shutil.move(site_path, new_path)
                site_path = new_path

    # Verify with nginx -t
    test_proc = subprocess.run([binary, "-t"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, timeout=10)
    if test_proc.returncode == 0:
        # Reload
        subprocess.run(["systemctl", "reload", "nginx"], timeout=10)
        res["success"] = True
        res["isEnabled"] = to_enable
        res["message"] = "Site state updated and Nginx reloaded successfully."
    else:
        # Revert
        res["success"] = False
        res["message"] = "Nginx syntax test failed after toggling site. State unchanged."
except Exception as e:
    res["message"] = str(e)

print("===TOGGLE_JSON_START===")
print(json.dumps(res))
print("===TOGGLE_JSON_END===")
PYEOF
`;

  try {
    const rawOut = await runAdaptiveSshCommand(server, script, ephemeralPassword, 15000);
    if (rawOut.includes('===TOGGLE_JSON_START===') && rawOut.includes('===TOGGLE_JSON_END===')) {
      const jsonStr = rawOut.split('===TOGGLE_JSON_START===')[1].split('===TOGGLE_JSON_END===')[0].trim();
      return JSON.parse(jsonStr);
    }
  } catch (err: any) {
    return { success: false, isEnabled: !enable, message: err?.message || 'Failed to toggle site' };
  }

  return { success: false, isEnabled: !enable, message: 'Failed to toggle site status' };
}

/**
 * Safely removes a site configuration file and its symlink
 */
export async function deleteNginxSite(
  server: RemoteServer,
  siteFilePath: string,
  ephemeralPassword?: string
): Promise<{ success: boolean; message: string }> {
  const discovery = await discoverNginxInstallation(server, ephemeralPassword);
  const nginxBinary = discovery.binaryPath || '/usr/sbin/nginx';

  const script = `python3 - << 'PYEOF'
import os, sys, subprocess, shutil, json

binary = "${nginxBinary}"
site_path = "${siteFilePath}"

res = {"success": False, "message": ""}

try:
    filename = os.path.basename(site_path)
    symlink_path = os.path.join("/etc/nginx/sites-enabled", filename)
    
    if os.path.islink(symlink_path) or os.path.exists(symlink_path):
        os.remove(symlink_path)
        
    if os.path.exists(site_path):
        os.remove(site_path)

    # Test & Reload
    test_proc = subprocess.run([binary, "-t"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, timeout=10)
    if test_proc.returncode == 0:
        subprocess.run(["systemctl", "reload", "nginx"], timeout=10)
        res["success"] = True
        res["message"] = "Site removed successfully and Nginx reloaded."
    else:
        res["success"] = True
        res["message"] = "Site deleted, but Nginx syntax test returned warning."
except Exception as e:
    res["message"] = str(e)

print("===DELETE_JSON_START===")
print(json.dumps(res))
print("===DELETE_JSON_END===")
PYEOF
`;

  try {
    const rawOut = await runAdaptiveSshCommand(server, script, ephemeralPassword, 15000);
    if (rawOut.includes('===DELETE_JSON_START===') && rawOut.includes('===DELETE_JSON_END===')) {
      const jsonStr = rawOut.split('===DELETE_JSON_START===')[1].split('===DELETE_JSON_END===')[0].trim();
      return JSON.parse(jsonStr);
    }
  } catch (err: any) {
    return { success: false, message: err?.message || 'Failed to delete site file' };
  }

  return { success: false, message: 'Failed to delete site' };
}
